on:
  repository_dispatch:
jobs:
  quicken:
    runs-on: ubuntu-latest
    steps:
    - uses: benluddy/highlander-action@v1-staging
      with:
        github_token: ${{ github.token }}
        repository: ${{ github.repository }}
        workflow_name: ${{ github.workflow }}
        workflow_run_number: ${{ github.run_number }}
    - run: 'sleep 60'
